### PR TITLE
Update Rust version to 1.87.0 on v1.0.2

### LINKED ISSUE #2096: cairo-vm 1.0.2 cannot be compiled with Rust 1.87.0
**Describe the bug**
`cairo-vm` 1.0.2 cannot be compiled with Rust 1.87.0.

**To Reproduce**
```
cargo check --workspace --all-targets
[...]
error[E0308]: mismatched types
  --> /home/hidden/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cairo-vm-1.0.2/src/hint_processor/builtin_hint_processor/signature.rs:32:25
   |
32 |         .is_multiple_of(&(CELLS_PER_SIGNATURE as usize))
   |          -------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `usize`, found `&usize`
   |          |
   |          arguments to this method are incorrect
   |
note: method defined here
  --> /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/num/mod.rs:1218:5
   = note: this error originates in the macro `uint_impl` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider removing the borrow
   |
32 -         .is_multiple_of(&(CELLS_PER_SIGNATURE as usize))
32 +         .is_multiple_of((CELLS_PER_SIGNATURE as usize))
   |

error[E0308]: mismatched types
   --> /home/hidden/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cairo-vm-1.0.2/src/vm/runners/cairo_pie.rs:623:44
    |
623 |             if !bytes.len().is_multiple_of(&CELL_BYTE_LEN) {
    |                             -------------- ^^^^^^^^^^^^^^ expected `usize`, found `&usize`
    |                             |
    |                             arguments to this method are incorrect
    |
note: method defined here
   --> /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/num/mod.rs:1218:5
    = note: this error originates in the macro `uint_impl` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider removing the borrow
    |
623 -             if !bytes.len().is_multiple_of(&CELL_BYTE_LEN) {
623 +             if !bytes.len().is_multiple_of(CELL_BYTE_LEN) {
    |

For more information about this error, try `rustc --explain E0308`.
error: could not compile `cairo-vm` (lib) due to 2 previous errors
[...]
```

**Expected behavior**
It'd be great to have cairo-vm 1.0.3, that is fully compatible with 1.0.2 but compiles with Rust 1.87.0.

**What version/commit are you on?**
v1.0.2

**Additional context**
We're using `cairo-vm` as a dependency of [blockifier](https://crates.io/crates/blockifier/0.14.0-rc.3). Because of this we cannot upgrade to non-compatible versions.

This issue blocks us from upgrading to a more recent version of Rust (we're on 1.85 right now).

### PR DESCRIPTION
**Pull request by DiegoCivi**
# Update Rust version to 1.87.0 on v1.0.2

## Description

Updates the version of Rust to 1.87.0 and solves compiling errors

Fixes #2096 

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
  - [ ] CHANGELOG has been updated.

### CODE REVIEW

File: examples/wasm-demo/Cargo.toml [hunk 1]
```diff
@@ -17,7 +17,7 @@ default = ["console_error_panic_hook"]
 
 [dependencies]
 serde_json.workspace = true
-wasm-bindgen = "0.2.87"
```
Comment (DiegoCivi) [inline examples/wasm-demo/Cargo.toml:20]: This was done because after the rust version upgrade, wasm tests failed. This solves that problem. Sme with `wasm-bindgen-test`

File: vm/src/tests/cairo_pie_test.rs [hunk 2]
```diff
@@ -6,12 +6,6 @@ use crate::{
 #[cfg(target_arch = "wasm32")]
 use wasm_bindgen_test::*;
 
-#[cfg(all(not(feature = "std"), feature = "alloc"))]
-use alloc::{
-    string::{String, ToString},
-    vec::Vec,
-};
-
```
Comment (DiegoCivi) [inline vm/src/tests/cairo_pie_test.rs]: This was not beinh used. On main it was also removed.

File: vm/src/tests/cairo_pie_test.rs [hunk 3]
```diff
@@ -25,12 +19,6 @@ use crate::{
     },
 };
 
-#[cfg(all(not(feature = "std"), feature = "alloc"))]
-use alloc::{
-    string::{String, ToString},
-    vec::Vec,
-};
-
```
Comment (DiegoCivi) [inline vm/src/tests/cairo_pie_test.rs]: Same here

File: vm/src/cairo_run.rs [hunk 4]
```diff
@@ -136,9 +140,9 @@ pub fn cairo_run_pie(
     if cairo_run_config.proof_mode {
         return Err(RunnerError::CairoPieProofMode.into());
     }
-    if !hint_processor
+    if hint_processor
         .get_n_steps()
-        .is_some_and(|steps| steps == pie.execution_resources.n_steps)
+        .is_none_or(|steps| steps != pie.execution_resources.n_steps)
```
Comment (FrancoGiachetta) [inline vm/src/cairo_run.rs:145]: Why was this changed?

File: vm/src/hint_processor/cairo_1_hint_processor/hint_processor.rs [hunk 5]
```diff
@@ -1,3 +1,8 @@
+// ark-ff-macros mess workaround
+// can't put this directly above MontConfig derive because Rust can't parse it correctly.
+#![allow(non_local_definitions)]
+#![allow(unexpected_cfgs)]
+
```
Comment (FrancoGiachetta) [inline vm/src/hint_processor/cairo_1_hint_processor/hint_processor.rs:5]: I don't know if this change is correct as it affects the whole file instead of just the struct you need. Does clippy complain about it?

File: vm/src/tests/mod.rs [hunk 6]
```diff
@@ -25,9 +25,6 @@ use crate::{
 #[cfg(target_arch = "wasm32")]
 use wasm_bindgen_test::*;
 
-#[cfg(all(not(feature = "std"), feature = "alloc"))]
-use alloc::{string::String, vec::Vec};
-
```
Comment (FrancoGiachetta) [inline vm/src/tests/mod.rs]: Why was this removed?

File: vm/src/tests/cairo_pie_test.rs (hunk 2 above)
Comment (gabrielbosio) [reply vm/src/tests/cairo_pie_test.rs]: I would do this in another PR

File: vm/src/tests/cairo_pie_test.rs (hunk 3 above)
Comment (gabrielbosio) [reply vm/src/tests/cairo_pie_test.rs]: I would do this in another PR

File: vm/src/cairo_run.rs (hunk 4 above)
Comment (DiegoCivi) [reply vm/src/cairo_run.rs:145]: It was suggested by clippy ([here](https://github.com/lambdaclass/cairo-vm/actions/runs/15424775701/job/43409209917#step:8:805))

File: cairo1-run/src/cairo_run.rs [hunk 7]
```diff
@@ -1447,8 +1447,8 @@ fn serialize_output_inner<'a>(
                 output_string.push(':');
                 // Serialize the value
                 // We create a peekable array here in order to use the serialize_output_inner as the value could be a span
-                let value_vec = vec![value.clone()];
-                let mut value_iter = value_vec.iter().peekable();
+                let value_arr = [value.clone()];
```
Comment (gabrielbosio) [inline cairo1-run/src/cairo_run.rs]: While `v1.0.2` is a branch of [main](https://github.com/lambdaclass/cairo-vm/blob/7c1b9d92b703226e5fcaac30b36bc7fbd17369e4/cairo1-run/src/cairo_run.rs#L1476) I would leave it as it is in main to decrease diffs between both branches:

```suggestion
                let value_vec = [value.clone()];
```

File: cairo1-run/src/cairo_run.rs [hunk 8]
```diff
@@ -1493,8 +1493,8 @@ fn serialize_output_inner<'a>(
...
```
Comment (gabrielbosio) [inline cairo1-run/src/cairo_run.rs]: While `v1.0.2` is a branch of [main](https://github.com/lambdaclass/cairo-vm/blob/7c1b9d92b703226e5fcaac30b36bc7fbd17369e4/cairo1-run/src/cairo_run.rs#L1522) I would leave it as it is in main to decrease diffs between both branches:

```suggestion
                let value_vec = [value.clone()];
```

File: vm/src/tests/mod.rs (hunk 6 above)
Comment (DiegoCivi) [reply vm/src/tests/mod.rs]: My bad, we should keep the `vec::Vec`. Thanks! Done in [`b075fcc`](https://github.com/lambdaclass/cairo-vm/pull/2112/commits/b075fcc10ebb37110d29be928b61d06ace1cdaa6)

File: vm/src/hint_processor/cairo_1_hint_processor/hint_processor.rs (hunk 5 above)
Comment (DiegoCivi) [reply vm/src/hint_processor/cairo_1_hint_processor/hint_processor.rs:5]: Yes, it can be seen [here](https://github.com/lambdaclass/cairo-vm/actions/runs/15476425214/job/43572813276#step:6:294). In main we are doing the same. It was done in #1990

File: cairo1-run/src/cairo_run.rs (hunk 7 above)
Comment (DiegoCivi) [reply cairo1-run/src/cairo_run.rs]: Done in [`0e59237`](https://github.com/lambdaclass/cairo-vm/pull/2112/commits/0e59237578e57647b5f6e8b5a7421faa2b171f41)

**Review by gabrielbosio — APPROVED** [review]

File: vm/src/vm/vm_memory/memory.rs [hunk 9]
```diff
@@ -32,10 +32,10 @@ pub struct ValidationRule(
...
 /// - BIT62: ACCESS flag, 1 when the cell has been accessed in a way observable to Cairo.
 /// - BIT61: RELOCATABLE flag, 1 when the contained value is a `Relocatable`, 0 when it is a
-/// `Felt252`.
-/// `Felt252` values are stored in big-endian order to keep the flag bits free.
-/// `Relocatable` values are stored as native endian, with the 3rd word storing the segment index
-/// and the 4th word storing the offset.
+///   `Felt252`.
+///   `Felt252` values are stored in big-endian order to keep the flag bits free.
+///   `Relocatable` values are stored as native endian, with the 3rd word storing the segment index
+///   and the 4th word storing the offset.
```
Comment (JulianGCalderon) [inline vm/src/vm/vm_memory/memory.rs]: Why was this comment changed?

File: vm/src/vm/vm_memory/memory.rs [hunk 10]
```diff
@@ -435,8 +435,8 @@ impl Memory {
     /// - `lhs` exists in memory but `rhs` doesn't -> (Ordering::Greater, 0)
     /// - `rhs` exists in memory but `lhs` doesn't -> (Ordering::Less, 0)
     /// - None of `lhs` or `rhs` exist in memory -> (Ordering::Equal, 0)
-    /// Everything else behaves much like `memcmp` in C.
-    /// This is meant as an optimization for hints to avoid allocations.
+    ///   Everything else behaves much like `memcmp` in C.
+    ///   This is meant as an optimization for hints to avoid allocations.
```
Comment (JulianGCalderon) [inline vm/src/vm/vm_memory/memory.rs]: Why was this changed?

File: vm/src/vm/vm_memory/memory.rs [hunk 11]
```diff
@@ -487,8 +487,9 @@ impl Memory {
     /// - `lhs` exists in memory but `rhs` doesn't -> (Ordering::Greater, 0)
     /// - `rhs` exists in memory but `lhs` doesn't -> (Ordering::Less, 0)
     /// - None of `lhs` or `rhs` exist in memory -> (Ordering::Equal, 0)
+    ///   
     /// Everything else behaves much like `memcmp` in C.
-    /// This is meant as an optimization for hints to avoid allocations.
+    ///   This is meant as an optimization for hints to avoid allocations.
```
Comment (JulianGCalderon) [inline vm/src/vm/vm_memory/memory.rs]: Why was this changed?

File: vm/src/vm/vm_memory/memory.rs (hunk 9 above)
Comment (DiegoCivi) [reply vm/src/vm/vm_memory/memory.rs]: It was a clippy suggestion. I tried to do a workaround by adding a blank line, but it kept complaining. ([here](https://github.com/lambdaclass/cairo-vm/actions/runs/15425729779/job/43412088050#step:8:754)). This was also done in main

File: vm/src/vm/vm_memory/memory.rs (hunk 10 above)
Comment (DiegoCivi) [reply vm/src/vm/vm_memory/memory.rs]: Same reason as above

File: vm/src/vm/vm_memory/memory.rs (hunk 9 above)
Comment (JulianGCalderon) [reply vm/src/vm/vm_memory/memory.rs]: Mmh, it doesn't make much sense to me. Adding spaces would impliy that the following paragraphs belong to the list item, which is not the case.

Did you try this:
```
/// - BIT61: RELOCATABLE flag, 1 when the contained value is a `Relocatable`, 0 when it is a
///   `Felt252`.
///
/// `Felt252` values are stored in big-endian order to keep the flag bits free.
/// `Relocatable` values are stored as native endian, with the 3rd word storing the segment index
/// and the 4th word storing the offset.
```

Note that:
- The second line should be indented, so that it belongs to the list item.
- We need an empty line to separate inner list content from the rest of the content.
- The last lines should not be indented.

If we missed it, we should probably fix it in main too.

Comment (JulianGCalderon) [reply vm/src/vm/vm_memory/memory.rs]: An alternative would be to keep the list content in a single line:
```
/// - BIT61: RELOCATABLE flag, 1 when the contained value is a `Relocatable`, 0 when it is a `Felt252`.
///
/// `Felt252` values are stored in big-endian order to keep the flag bits free.
/// `Relocatable` values are stored as native endian, with the 3rd word storing the segment index
/// and the 4th word storing the offset.
```

Comment (DiegoCivi) [reply vm/src/vm/vm_memory/memory.rs]: I was wrong, it actually works. I was pretty sure i tried it and it break. Thanks! Done in [`9ee64eb`](https://github.com/lambdaclass/cairo-vm/pull/2112/commits/9ee64eb8963b47dc98e3ef6c75e59444f29cea3a)

Comment (JulianGCalderon) [reply vm/src/vm/vm_memory/memory.rs]: Great. Can you fix it in main also?
