### ISSUE TITLE
cairo-vm 1.0.2 cannot be compiled with Rust 1.87.0

### ISSUE THREAD

**Issue by kkovaacs** [lambdaclass/cairo-vm#2096]
**Describe the bug**
`cairo-vm` 1.0.2 cannot be compiled with Rust 1.87.0.

**To Reproduce**
```
cargo check --workspace --all-targets
[...]
error[E0308]: mismatched types
  --> /home/hidden/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cairo-vm-1.0.2/src/hint_processor/builtin_hint_processor/signature.rs:32:25
   |
32 |         .is_multiple_of(&(CELLS_PER_SIGNATURE as usize))
   |          -------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `usize`, found `&usize`
   |          |
   |          arguments to this method are incorrect
   |
note: method defined here
  --> /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/num/mod.rs:1218:5
   = note: this error originates in the macro `uint_impl` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider removing the borrow
   |
32 -         .is_multiple_of(&(CELLS_PER_SIGNATURE as usize))
32 +         .is_multiple_of((CELLS_PER_SIGNATURE as usize))
   |

error[E0308]: mismatched types
   --> /home/hidden/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cairo-vm-1.0.2/src/vm/runners/cairo_pie.rs:623:44
    |
623 |             if !bytes.len().is_multiple_of(&CELL_BYTE_LEN) {
    |                             -------------- ^^^^^^^^^^^^^^ expected `usize`, found `&usize`
    |                             |
    |                             arguments to this method are incorrect
    |
note: method defined here
   --> /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/num/mod.rs:1218:5
    = note: this error originates in the macro `uint_impl` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider removing the borrow
    |
623 -             if !bytes.len().is_multiple_of(&CELL_BYTE_LEN) {
623 +             if !bytes.len().is_multiple_of(CELL_BYTE_LEN) {
    |

For more information about this error, try `rustc --explain E0308`.
error: could not compile `cairo-vm` (lib) due to 2 previous errors
[...]
```

**Expected behavior**
It'd be great to have cairo-vm 1.0.3, that is fully compatible with 1.0.2 but compiles with Rust 1.87.0.

**What version/commit are you on?**
v1.0.2

**Additional context**
We're using `cairo-vm` as a dependency of [blockifier](https://crates.io/crates/blockifier/0.14.0-rc.3). Because of this we cannot upgrade to non-compatible versions.

This issue blocks us from upgrading to a more recent version of Rust (we're on 1.85 right now).

**Comment by gabrielbosio** [comment]
Fixed in #2112
